init:
  - git config --global core.autocrlf true
branches:
  only:
    - dev
    - /^(.*\/)?ci-.*$/
    - /^rel\/.*/
configuration:
  - Debug
  - Release
matrix:
  fast_finish: true
build_script:
  - ps: .\run.ps1 default-build /P:Configuration=%Configuration%
clone_depth: 1
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
deploy: off
image: Visual Studio 2017
