//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNetCore.WebHooks {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlStorageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal SqlStorageResource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNetCore.WebHooks.Custom.SqlStorage.SqlStorageResource", typeof(SqlStorageResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The &apos;{0}&apos; could not be retrieved from the SQL store: {1}.
        /// </summary>
        public static string SqlStore_BadWebHook {
            get {
                return ResourceManager.GetString("SqlStore_BadWebHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Concurrency failure during &apos;{0}&apos; operation: &apos;{1}&apos;..
        /// </summary>
        public static string SqlStore_ConcurrencyError {
            get {
                return ResourceManager.GetString("SqlStore_ConcurrencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please provide an Azure Table Storage connection string with name &apos;{0}&apos; in the configuration string section of the &apos;Web.Config&apos; file..
        /// </summary>
        public static string SqlStore_NoConnectionString {
            get {
                return ResourceManager.GetString("SqlStore_NoConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to General error during &apos;{0}&apos; operation: &apos;{1}&apos;..
        /// </summary>
        public static string SqlStore_OperationFailed {
            get {
                return ResourceManager.GetString("SqlStore_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Operation &apos;{0}&apos; failed with error: &apos;{1}&apos;..
        /// </summary>
        public static string SqlStore_SqlOperationFailed {
            get {
                return ResourceManager.GetString("SqlStore_SqlOperationFailed", resourceCulture);
            }
        }
    }
}
