// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Net.Http;
using System.Web.Http.Controllers;
using Microsoft.AspNet.WebHooks.Receivers.TFS.WebHooks.Payloads;
using Newtonsoft.Json.Linq;
using System.Globalization;
using Microsoft.AspNet.WebHooks.Properties;

namespace Microsoft.AspNet.WebHooks.Receivers.TFS.WebHooks
{
    /// <summary>
    /// Provides an <see cref="IWebHookReceiver"/> implementation which supports WebHooks generated by Visual Studio Team Services. 
    /// 
    /// The corresponding WebHook URI is of the form '<c>https://&lt;host&gt;/api/webhooks/incoming/tfs/{id}?code={code}</c>'.
    /// For security reasons the WebHook URI must be an <c>https</c> URI and contain a 'code' query parameter with the
    /// same value as configured in the '<c>MS_WebHookReceiverSecret_Tfs</c>' application setting, optionally using IDs
    /// to differentiate between multiple WebHooks, for example '<c>secret0, id1=secret1, id2=secret2</c>'.
    /// The 'code' parameter must be between 32 and 128 characters long.
    /// 
    /// For details about Visual Studio Team Services WebHooks, see <c>https://www.visualstudio.com/en-us/get-started/integrate/service-hooks/webhooks-and-vso-vs</c>.
    /// </summary>
    class TfsWebHookReceiver : WebHookReceiver
    {
        internal const string RecName = "tfs";
        internal const string RequestIdHeaderName = "X-Request-Id";

        internal const string EventTypeTokenName = "eventType";

        internal readonly Dictionary<string, Type> _eventsTypes;

        /// <summary>
        /// Initializes a new instance of the <see cref="TfsWebHookReceiver"/> class.
        /// </summary>
        public TfsWebHookReceiver()
        {
            _eventsTypes = new Dictionary<string, Type>() {
                { "workitem.updated", typeof(WorkItemUpdatedPayload) },
                { "workitem.restored", typeof(WorkItemRestoredPayload) },
                { "workitem.deleted", typeof(WorkItemDeletedPayload) },
                { "workitem.created", typeof(WorkItemCreatedPayload) },
                { "workitem.commented", typeof(WorkItemCommentedOnPayload) },
                { "message.posted", typeof(TeamRoomMessagePostedPayload) },
                { "tfvc.checkin", typeof(CodeCheckedInPayload) },
                { "build.complete", typeof(BuildCompletedPayload) } };
        }

        /// <summary>
        /// Gets the receiver name for this receiver.
        /// </summary>
        public static string ReceiverName
        {
            get { return RecName; }
        }

        /// <inheritdoc />
        public override string Name
        {
            get { return RecName; }
        }

        /// <inheritdoc />
        public override async Task<HttpResponseMessage> ReceiveAsync(string id, HttpRequestContext context, HttpRequestMessage request)
        {
            if (id == null)
            {
                throw new ArgumentNullException(nameof(id));
            }
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }
            if (request == null)
            {
                throw new ArgumentNullException(nameof(request));
            }

            if (request.Method != HttpMethod.Post)
            {
                return CreateBadMethodResponse(request);
            }

            // Ensure that we use https and have a valid code parameter
            await EnsureValidCode(request, id);

            // Read the request entity body
            JToken rawJsonData = await ReadAsJsonTokenAsync(request);
            string action = rawJsonData.SelectToken(EventTypeTokenName)?.Value<string>();

            // Map eventType to payload and call registered handlers with appropriate parameter type
            if (String.IsNullOrEmpty(action))
            {
                request.GetConfiguration().DependencyResolver.GetLogger().Error(TfsReceiverResources.Receiver_NoEventType);
                return CreateBadMethodResponse(request);
            }
            else if (!_eventsTypes.ContainsKey(action))
            {
                string msg = string.Format(CultureInfo.CurrentCulture, TfsReceiverResources.Receiver_NonMappedEventType, action);
                request.GetConfiguration().DependencyResolver.GetLogger().Warn(msg);
                return await ExecuteWebHookAsync(id, context, request, new[] { action }, rawJsonData.ToObject(_eventsTypes[action]));
            }
            else
            {
                return await ExecuteWebHookAsync(id, context, request, new[] { action }, rawJsonData);
            }
        }
    }
}
