// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http.Controllers;
using Microsoft.AspNet.WebHooks.Properties;
using Newtonsoft.Json.Linq;

namespace Microsoft.AspNet.WebHooks
{
    /// <summary>
    /// Provides an <see cref="IWebHookReceiver"/> implementation which supports WebHooks generated by Zendesk. 
    /// A sample WebHook URI is '<c>https://&lt;host&gt;/api/webhooks/incoming/Zendesk/{id}?code=83699ec7c1d794c0c780e49a5c72972590571fd8</c>'.
    /// For security reasons the WebHook URI must be an <c>https</c> URI and contain a 'code' query parameter with the
    /// same value as configured in the '<c>MS_WebHookReceiverSecret_Zendesk</c>' application setting.
    /// The 'code' parameter must be between 32 and 128 characters long.
    /// For details about Zendesk WebHooks, see <c>https://developer.zendesk.com/embeddables/docs/ios/push_notifications_webhook#webhook-api</c>.
    /// For complete details about Zendesk APIs, see <c>https://developer.zendesk.com/rest_api/docs/core/introduction</c>.
    /// </summary>
    public class ZendeskWebHookReceiver : WebHookReceiver
    {
        internal const string ReceiverName = "zendesk";

        internal const string RegisteredHeaderAppId = "AppId";
        internal const string ZendeskHeaderUrl = "zendeskUrl";
        internal const string ClientHeaderId = "ClientId";
        //internal const string WebHookIdKey = "webHook_id";

        /// <inheritdoc />
        public override string Name
        {
            get { return ReceiverName; }
        }

        /// <inheritdoc />
        public override async Task<HttpResponseMessage> ReceiveAsync(string id, HttpRequestContext context, HttpRequestMessage request)
        {
            if (id == null)
            {
                throw new ArgumentNullException("id");
            }
            if (context == null)
            {
                throw new ArgumentNullException("context");
            }
            if (request == null)
            {
                throw new ArgumentNullException("request");
            }

            if (request.Method == HttpMethod.Post)
            {
                // Ensure that we use https and have a valid code parameter
                await EnsureValidCode(request, id);

                // Read the request entity body.
                JObject data = await ReadAsJsonAsync(request);

                // Pick out appId from headers
                IEnumerable<string> actions;
                if (!request.Headers.TryGetValues(RegisteredHeaderAppId, out actions))
                {
                    string msg = string.Format(CultureInfo.CurrentCulture, ZendeskReceiverResources.Receiver_NoRegisteredAppId, RegisteredHeaderAppId);
                    context.Configuration.DependencyResolver.GetLogger().Error(msg);
                    HttpResponseMessage noEventHeader = request.CreateErrorResponse(HttpStatusCode.BadRequest, msg);
                    return noEventHeader;
                }

                // Pick out appId from headers
                IEnumerable<string> appId;
                if (!request.Headers.TryGetValues(RegisteredHeaderAppId, out appId))
                {
                    string msg = string.Format(CultureInfo.CurrentCulture, ZendeskReceiverResources.Receiver_NoRegisteredAppId, RegisteredHeaderAppId);
                    context.Configuration.DependencyResolver.GetLogger().Error(msg);
                    HttpResponseMessage noEventHeader = request.CreateErrorResponse(HttpStatusCode.BadRequest, msg);
                    return noEventHeader;
                }

                // Get the zendeskUrl
                IEnumerable<string> zendeskUrl;
                if (!request.Headers.TryGetValues(ZendeskHeaderUrl, out zendeskUrl))
                {
                    string msg = string.Format(CultureInfo.CurrentCulture, ZendeskReceiverResources.Receiver_NoUrl, ZendeskHeaderUrl);
                    context.Configuration.DependencyResolver.GetLogger().Error(msg);
                    HttpResponseMessage noWebHookIdHeader = request.CreateErrorResponse(HttpStatusCode.BadRequest, msg);
                    return noWebHookIdHeader;
                }

                // Get the ClientId
                IEnumerable<string> clientId;
                if (!request.Headers.TryGetValues(ClientHeaderId, out clientId))
                {
                    string msg = string.Format(CultureInfo.CurrentCulture, ZendeskReceiverResources.Receiver_NoClientId, clientId);
                    context.Configuration.DependencyResolver.GetLogger().Error(msg);
                    HttpResponseMessage noWebHookIdHeader = request.CreateErrorResponse(HttpStatusCode.BadRequest, msg);
                    return noWebHookIdHeader;
                }

                // Set the WebHook ID in the payload
               // data[WebHookIdKey] = webHookId.FirstOrDefault();

                // Call registered handlers
                return await ExecuteWebHookAsync(id, context, request, actions, data);
            }
            else
            {
                return CreateBadMethodResponse(request);
            }
        }
    }
}